### ISSUE TITLE
confused by weatherFX settings - how to fix time & date?

### ISSUE THREAD

**Issue by danpowpow** [compujuckel/AssettoServer#12]
Thanks so much for developing this amazing project! it's great to be able to spin up traffic servers for  freeroam cruises with friends in AC :-)
I'm having trouble setting the time of day though, specifically for night drives. Is this a feature that is not-yet implemented, or am I going about it wrong?!

in extra_cfg.yml, I have EnableWeatherFx: true

the server settings from content manager are
time = 8:00, time mulitplier=0x
Weather FX / clear / time: 19:00 , time mult 1x /  specific date 1st June (06/01/22)

these settings generate the following lines in server_cfg.ini:
SUN_ANGLE=-80
TIME_OF_DAY_MULT=0

[WEATHER_0]
GRAPHICS=3_clear_type=15_time=68400_start=1653955200
BASE_TEMPERATURE_AMBIENT=18
BASE_TEMPERATURE_ROAD=6
VARIATION_AMBIENT=2
VARIATION_ROAD=1
WIND_BASE_SPEED_MIN=0
WIND_BASE_SPEED_MAX=0
WIND_BASE_DIRECTION=0
WIND_VARIATION_DIRECTION=0
__CM_GRAPHICS=3_clear
__CM_WFX_TYPE=15
__CM_WFX_USE_CUSTOM_TIME=1
__CM_WFX_TIME=68400
__CM_WFX_TIME_MULT=1
__CM_WFX_USE_CUSTOM_DATE=1
__CM_WFX_DATE=1654038000

Assetto Server runs, but with the following warning, and it's 8am in game.
[11:20:59 WRN] Do not use WeatherFX start times or time multipliers. Use the original config values instead

EnableRealTime: true works, and gives me Tokyo time - which if in the evening works ie is dark.

Any insight would be appreciated :-)

content manager 0.8.2358.38968 (x86), csp 176 preview, assetto server 0.0.46+280b6db74f

**Comment by compujuckel** [comment]
First of all if you don't care about rain etc. just disable EnableWeatherFx and the time should work as intended.

otherwise, just to what the warning says: remove start time from your WeatherFX weather type.
(`GRAPHICS` should not contain `_time` or `_mult`)

those WeatherFX values are basically a hack for the original acserver to allow night time even though the server doesn't support sun angle values outside of 8am and 6pm.

This restriction does not exist with AssettoServer. You can set `SUN_ANGLE=96` and it should work properly.

**Comment by danpowpow** [comment]
thanks so much @compujuckel - setting SUN_ANGLE gets the required result. You're absolutely right :-)

SUN_ANGLE=-330
TIME_OF_DAY_MULT=35

the above gets a sunset->night freeroam in shutoko - just what I was looking for!

**Comment by unflood123** [comment]
i need help setting up night and day on my server

does anybody know the correct setting also while using rain fx[
![sss](https://user-images.githubusercontent.com/100457280/155828788-fa7bc586-a1e8-4512-907b-51ec1d617162.PNG)
](url)
