### ISSUE TITLE
Bundling AssettoServer with config files

### ISSUE THREAD

**Issue by nventstudios** [compujuckel/AssettoServer#88]
Hello,

I'm creating a repository on my GitHub page including base files for those wishing to run an SRP free-roam server but not wanting to go through the hassle of packing their own server and such.
I wanted to know if I could include a version of AssettoServer with those files? I wasn't sure of the stance of me packaging it (obviously with credit, I'm not going to masquerade the software as mine) so I wished to ask first just in case.

**Comment by compujuckel** [comment]
Hi, thanks for reaching out!
In general I'm not a big fan of other people redistributing server binaries, because it is hard for users to check the legitimacy of the files. That's just my personal opinion though, in the end you're still allowed to include binaries if you want. 
An alternative could be to tell people which server version your presets are tested with and link the official download instead.

**Comment by blvdcode** [comment]
Hello again, sorry for the late reply. I will include a link to the AssettoServer link and Github in my presets - hopefully that's sufficient enough. I've also linked donation links in the repository once I finally finish it and set it up to go live :)

**Comment by blvdcode** [comment]
Solved

**Comment by blvdcode** [comment]
Whoops
